In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day28-column-transformer/covid_toy.csv")

In [4]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isna().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
df.cough.value_counts()

Mild      62
Strong    38
Name: cough, dtype: int64

In [7]:
x=df.iloc[:,:-1]

In [8]:
y=df.iloc[:,-1]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)

In [10]:
x_train

age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
39   50  Female  103.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
18   64  Female   98.0    Mild  Bangalore
59    6  Female  104.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
28   16    Male  104.0    Mild    Kolkata
49   44    Male  104.0    Mild     Mumbai
12   25  Female   99.0  Strong    Kolkata
90   59  Female   99.0  Strong      Delhi
26   19  Female  100.0    Mild    Kolkata

[80 rows x 5 columns]

In [11]:
x_train.cough

0       Mild
39      Mild
42      Mild
18      Mild
59      Mild
       ...  
28      Mild
49      Mild
12    Strong
90    Strong
26      Mild
Name: cough, Length: 80, dtype: object

# 1.Aam Zindagi

In [12]:
si=SimpleImputer()
x_train_fever=si.fit_transform(x_train[["fever"]])
x_test_fever=si.transform(x_test[["fever"]])

In [13]:
x_test_fever

array([[102.        ],
       [102.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [100.91549296],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [ 99.        ],
       [104.        ],
       [ 98.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [102.        ],
       [101.        ],
       [101.        ],
       [101.        ]])

In [14]:
oe=OrdinalEncoder(categories=[["Mild","Strong"]])
x_train_cough=oe.fit_transform(x_train[["cough"]])
x_test_cough=oe.transform(x_test[["cough"]])

x_train_cough.shape

(80, 1)

In [15]:
ohe=OneHotEncoder(drop="first",sparse=False)
x_train_city=ohe.fit_transform(x_train[["gender","city"]])
x_test_city=ohe.transform(x_test[["gender","city"]])

In [16]:
x_train_city

array([[1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],


In [17]:
x_train_transformed=np.concatenate((x_train[["age"]],x_train_fever,x_train_city,x_train_cough),axis=1)
x_test_transformed=np.concatenate((x_test[["age"]],x_test_fever,x_test_city,x_test_cough),axis=1)

In [18]:
x_train_transformed

array([[ 60.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 50.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 64.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [  6.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 48.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 47.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 38.        , 100.91549296,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 51.        , 104.        ,   1.        ,   0.        ,
          0.    

In [19]:
# np.hstack(x_train[["age"]].values,x_train_fever.values,x_train_fever.values,x_train_city.values,x_train_cough.values)

# Mentos Zindagi

In [20]:
df=pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day28-column-transformer/covid_toy.csv")

In [21]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [22]:
from sklearn.compose import ColumnTransformer

In [23]:
transformer=ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(),["fever"]),
    ("tnf2",OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),
    ("tnf3",OneHotEncoder(sparse=False,drop="first"),["gender","city"])

],remainder="passthrough")

In [24]:
transformer.fit_transform(x_train[["fever","cough","gender","city"]])

array([[103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ],
       [ 98.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [100.91549296,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0. 

In [25]:
pd.DataFrame(transformer.fit_transform(x_train))

0    1    2    3    4    5     6
0   103.0  0.0  1.0  0.0  1.0  0.0  60.0
1   103.0  0.0  0.0  0.0  1.0  0.0  50.0
2   100.0  0.0  1.0  1.0  0.0  0.0  27.0
3    98.0  0.0  0.0  0.0  0.0  0.0  64.0
4   104.0  0.0  0.0  0.0  1.0  0.0   6.0
..    ...  ...  ...  ...  ...  ...   ...
75  104.0  0.0  1.0  0.0  1.0  0.0  16.0
76  104.0  0.0  1.0  0.0  0.0  1.0  44.0
77   99.0  1.0  0.0  0.0  1.0  0.0  25.0
78   99.0  1.0  0.0  1.0  0.0  0.0  59.0
79  100.0  0.0  0.0  0.0  1.0  0.0  19.0

[80 rows x 7 columns]

In [26]:
x_train

age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
39   50  Female  103.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
18   64  Female   98.0    Mild  Bangalore
59    6  Female  104.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
28   16    Male  104.0    Mild    Kolkata
49   44    Male  104.0    Mild     Mumbai
12   25  Female   99.0  Strong    Kolkata
90   59  Female   99.0  Strong      Delhi
26   19  Female  100.0    Mild    Kolkata

[80 rows x 5 columns]

In [27]:
pd.set_option("display.max_rows",None)

In [28]:
df=pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day28-column-transformer/covid_toy.csv")

In [29]:
df.fever

0     103.0
1     100.0
2     101.0
3      98.0
4     101.0
5       NaN
6     101.0
7       NaN
8     100.0
9     101.0
10      NaN
11     98.0
12     99.0
13    102.0
14    104.0
15    103.0
16    103.0
17     98.0
18     98.0
19      NaN
20     98.0
21     98.0
22     98.0
23     98.0
24    100.0
25      NaN
26    100.0
27    102.0
28    104.0
29      NaN
30    101.0
31    103.0
32    101.0
33     98.0
34    102.0
35    102.0
36    101.0
37    100.0
38    101.0
39    103.0
40    102.0
41      NaN
42    100.0
43     99.0
44    102.0
45     99.0
46    101.0
47    104.0
48     99.0
49    104.0
50    101.0
51    100.0
52    100.0
53     98.0
54     99.0
55    101.0
56      NaN
57     99.0
58     98.0
59    104.0
60    102.0
61     98.0
62    104.0
63    100.0
64    104.0
65    102.0
66    104.0
67     99.0
68    104.0
69    103.0
70    101.0
71    104.0
72    101.0
73     98.0
74    104.0
75    102.0
76    100.0
77    101.0
78    100.0
79    103.0
80     99.0
81     99.0
82     98.0
83  

In [30]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [31]:
si=SimpleImputer()

In [32]:
df["fever"]=si.fit_transform(df[["fever"]])

In [33]:
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [34]:
df.isna().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [35]:
x=df.iloc[:,:-1]

In [36]:
y=df.iloc[:,-1]

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.3,random_state=1)

In [39]:
x_train.head()

age  gender  fever   cough       city
67   65    Male   99.0    Mild  Bangalore
99   10  Female   98.0  Strong    Kolkata
54   60  Female   99.0    Mild     Mumbai
95   12  Female  104.0    Mild  Bangalore
88    5  Female  100.0    Mild    Kolkata

In [40]:
transformer=ColumnTransformer(transformers=[
    ("tnf1",SimpleImputer(),["fever"]),
    ("tnf2",OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),
    ("tnf3",OneHotEncoder(sparse=False,drop="first"),["gender","city"])

],remainder="passthrough")

In [41]:
from sklearn.compose import ColumnTransformer

In [42]:
transformer=ColumnTransformer(transformers=[
     ('tnf1',OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),
    ('tnf2',OneHotEncoder(sparse=False,drop="first"),["gender","city"])
],remainder="passthrough")

In [44]:
transformer.fit_transform(x_train[["cough","gender","city"]])

array([[0., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 0.],
       [0., 1., 1., 0., 0.],
       [0., 0.