In [1]:
from sklearn.datasets import load_diabetes
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split


In [2]:
X,y=load_diabetes( return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [4]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=2)

In [5]:
reg=LinearRegression()

In [6]:
reg.fit(x_train,y_train)

LinearRegression()

In [7]:
x_train.shape

(353, 10)

In [8]:
reg.coef_

array([  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
       -895.54360867,  561.21453306,  153.88478595,  126.73431596,
        861.12139955,   52.41982836])

In [9]:
reg.intercept_

151.88334520854633

In [10]:
y_pred=reg.predict(x_test)

In [11]:
r2_score(y_test,y_pred)

0.4399387660024645

In [71]:
class mini_batch_gd:
    def __init__(self,batch_size,learning_rate=.01,epochs=100):
        self.coef_=None
        self.intercept_=None
        self.lr=learning_rate
        self.epochs=epochs
        self.batch_size=batch_size
    def fit(self,x_train,y_train):
        self.intercept_=0
        self.coef_=np.ones(x_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(int(x_train.shape[0]/self.batch_size)):
                idx=random.sample(range(x_train.shape[0]),self.batch_size)
                #idx=np.random.randint(1,range(x_train.shape[0]),self.batch_size)
                y_hat=np.dot(x_train[idx],self.coef_)+self.intercept_ 
                #print(y_hat)
                intercept_der=-2*np.mean(y_train[idx]-y_hat)

                self.intercept_=self.intercept_-(self.lr*intercept_der)

                coef_der= -2*np.dot((y_train[idx]-y_hat),x_train[idx])/x_train.shape[0]
                self.coef_=self.coef_-(self.lr*coef_der)
        print(self.intercept_,self.coef_)
    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_
        

In [72]:
np.random.randint(1,100,10)

array([86, 15, 29, 30, 50, 35, 73, 82, 35, 92])

In [73]:
# import random
# random.sample(1,100,10)

In [74]:
x_train[[12, 52, 90, 33, 91, 23, 47, 13, 11, 55]]

array([[ 0.0090156 ,  0.05068012, -0.00512814, -0.06419941,  0.06998059,
         0.0838625 , -0.03971921,  0.07120998,  0.03953988,  0.01963284],
       [-0.02367725, -0.04464164,  0.03043966, -0.00567061,  0.08236416,
         0.09200436, -0.01762938,  0.07120998,  0.03304707,  0.00306441],
       [ 0.00538306,  0.05068012,  0.03043966,  0.08384403, -0.03734373,
        -0.0473467 ,  0.01550536, -0.03949338,  0.00864028,  0.01549073],
       [ 0.06713621,  0.05068012, -0.01482845,  0.05859631, -0.05935898,
        -0.03450761, -0.06180903,  0.01290621, -0.00514531,  0.04862759],
       [-0.01277963,  0.05068012, -0.05578531, -0.00222774, -0.02771206,
        -0.02918409,  0.019187  , -0.03949338, -0.0170521 ,  0.04448548],
       [ 0.01991321,  0.05068012,  0.10480869,  0.07007254, -0.03596778,
        -0.0266789 , -0.02499266, -0.00259226,  0.00371174,  0.04034337],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665645,  0.01219057,
         0.02499059, -0.03603757,  0.03430886

In [75]:
mbg=mini_batch_gd(batch_size=int(x_train.shape[0]/10),learning_rate=0.1,epochs=100)

In [76]:
mbg.fit(x_train,y_train)

146.62898107301507 [ 15.65074189   3.91842064  41.90662872  32.14649953  14.58759273
  11.2305497  -24.82734049  27.42505331  41.224343    24.77031114]


In [51]:
y_pred=mbg.predict(x_test)

In [52]:
r2_score(y_test,y_pred)

0.09784520415909459

In [53]:
from sklearn.linear_model import SGDRegressor

In [55]:
sgd=SGDRegressor(learning_rate="constant",eta0=.2)

In [77]:
batch_size=35
for i in range(100):
    idx=random.sample(range(x_train.shape[0]),batch_size)
    sgd.partial_fit(x_train[idx],y_train[idx])

In [78]:
sgd.coef_

array([  -4.00259447, -181.18021107,  509.15703377,  338.46818028,
        -72.78658028, -145.80911842, -191.87463994,   83.34881435,
        465.2303642 ,  102.14994023])

In [79]:
sgd.intercept_

array([148.80592076])

In [80]:
y_pred=sgd.predict(x_test)

In [82]:
r2_score(y_test,y_pred)

0.44668580101964317