In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [4]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
X.shape

(442, 10)

# using sklearn's linear Regression

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=2)

In [8]:
x_train.shape

(309, 10)

In [9]:
x_test.shape

(133, 10)

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
reg=LinearRegression()

In [12]:
reg.fit(x_train,y_train)

LinearRegression()

In [13]:
y_pred=reg.predict(x_test)

In [14]:
from sklearn.metrics import r2_score

In [15]:
r2_score(y_test,y_pred)

0.5012620528324084

In [16]:
reg.score(x_test,y_test)

0.5012620528324084

In [17]:
reg.coef_

array([ -31.80536962, -214.67167622,  445.13750645,  376.35494358,
       -802.45172889,  525.95185517,  106.39967097,  172.31122486,
        799.47904182,   57.16768747])

# Making own class

In [22]:
class meralr:
    def __init__(self):
        self.coef_=None
        self.intercept_=None
    def fit(self,x_train,y_train):
        x_train=np.insert(x_train,0,1,axis=1)
        betas=np.linalg.inv(np.dot(x_train.T,x_train)).dot((x_train.T).dot(y_train))
        self.intercept_=betas[0]
        self.coef_=betas[1:]
        print(betas)
    def predict(self,x_test):
        y_pred=np.dot(x_test,self.coef_)+self.intercept_
        return y_pred

In [23]:
lr=meralr()

In [24]:
lr.fit(x_train,y_train)

[ 152.62754194  -31.80536962 -214.67167622  445.13750645  376.35494358
 -802.45172889  525.95185517  106.39967097  172.31122486  799.47904182
   57.16768747]


In [25]:
lr.predict(x_test)

array([153.24537424, 204.26239453, 125.21081597, 108.22025298,
       256.03179654, 253.23323854, 117.42180956, 120.55273333,
        95.78750885, 190.06977442, 143.9656687 , 177.30193582,
       180.06723313, 135.90604692, 287.68304903,  90.25399564,
       212.08853302, 160.21767766, 134.88303419, 121.37057926,
       138.5740191 , 168.29390353, 163.21666738, 176.29350013,
       130.77477113, 226.7361735 , 195.60661642, 101.68383417,
        48.13884964, 240.04946188, 246.46456316, 120.18462254,
        71.53332653,  97.44511452, 202.48078577, 171.05376539,
       159.89998068, 196.22813855, 114.71858185, 242.26807026,
       134.78653302, 119.20962398, 193.32699504, 199.58892436,
       172.21225895, 151.01368177, 164.62256367, 281.49743177,
       104.14872837, 170.38407556, 254.31708693, 133.68638067,
       154.97442421, 114.96217894, 192.56745582,  82.7500241 ,
       131.99309163,  71.12058957, 161.07394217, 161.06656479,
       169.80398831, 158.3972346 ,  96.40340744, 238.32

In [26]:
r2_score(y_test,y_pred)

0.5012620528324084

In [27]:
lr.coef_

array([ -31.80536962, -214.67167622,  445.13750645,  376.35494358,
       -802.45172889,  525.95185517,  106.39967097,  172.31122486,
        799.47904182,   57.16768747])

In [28]:
lr.intercept_

152.62754194200335