In [1]:
from sklearn.datasets import load_diabetes
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import time

C:\Users\Abdur rahim nishad\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Abdur rahim nishad\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\Abdur rahim nishad\anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
X,y=load_diabetes(return_X_y=True)

In [3]:
X.shape

(442, 10)

In [4]:
y.shape

(442,)

In [5]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=2)

In [6]:
X_train

array([[-0.00188202, -0.04464164, -0.06979687, ..., -0.03949338,
        -0.06291688,  0.04034337],
       [-0.00914709, -0.04464164,  0.01103904, ..., -0.03949338,
         0.01703607, -0.0052198 ],
       [ 0.02354575,  0.05068012, -0.02021751, ..., -0.03949338,
        -0.09643495, -0.01764613],
       ...,
       [ 0.06350368,  0.05068012, -0.00405033, ..., -0.00259226,
         0.08449153, -0.01764613],
       [-0.05273755,  0.05068012, -0.01806189, ...,  0.1081111 ,
         0.03606033, -0.04249877],
       [ 0.00175052,  0.05068012,  0.05954058, ...,  0.1081111 ,
         0.06898589,  0.12732762]])

In [7]:
reg=LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [8]:
y_pred=reg.predict(X_test)

In [9]:
r2_score(y_test,y_pred)

0.4399338661568968

# amara code

In [10]:
class sgd_regressor:
    def __init__(self,learning_rate=.01,epochs=100):
        self.coef_=None
        self.intercept_=None
        self.lr=learning_rate
        self.epochs=epochs
    def fit(self,x_train,y_train):
        self.intercept_=0
        self.coef_=np.ones(x_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(X_train.shape[0]):
                idx=np.random.randint(0,X_train.shape[0])
                y_hat=np.dot(x_train[idx],self.coef_)+self.intercept_ 
                
                intercept_der=-2*(y_train[idx]-y_hat)
                self.intercept_=self.intercept_-(self.lr*intercept_der)
                
                coef_der= -2*np.dot((y_train[idx]-y_hat),x_train[idx])
                self.coef_=self.coef_-(self.lr*coef_der)
            
        
        
        print(self.intercept_,self.coef_)
    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+self.intercept_
        

In [11]:
sgd=sgd_regressor(learning_rate=.01,epochs=50)

In [12]:
start=time.time()
sgd.fit(X_train,y_train)
print("Time taken is:",time.time()-start)

152.5469325179033 [  56.96645982  -71.74420775  348.10106426  245.23884453   17.57032827
  -30.46979436 -168.37836911  127.48979211  314.99704013  130.49206609]
Time taken is: 0.6506268978118896


In [13]:
y_pred=sgd.predict(X_test)

In [14]:
r2_score(y_test,y_pred)

0.43408018692842465

# sklearn sgd 

In [15]:
from sklearn.linear_model import SGDRegressor

In [16]:
X,y=load_diabetes(return_X_y=True)

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=2)

In [18]:
reg=SGDRegressor(max_iter=100,learning_rate="constant",eta0=0.01)

In [19]:
reg.fit(X_train,y_train)

SGDRegressor(learning_rate='constant', max_iter=100)

In [20]:
y_pred=reg.predict(X_test)

In [21]:
r2_score(y_test,y_pred)

0.42410161326470475

In [26]:
np.random.randint(0,X_train.shape[0])

266

In [27]:
coef_=np.ones(X_train.shape[1])

In [32]:
coef_.shape

(10,)

In [33]:
coef_

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
X_train[266]

array([ 0.04170844,  0.05068012,  0.01966154,  0.05974375, -0.00569682,
       -0.00256647, -0.02867429, -0.00259226,  0.0311926 ,  0.00720652])

In [34]:
X_train[266].shape

(10,)

In [30]:
intercept_=0

In [31]:
np.dot(X_train[266],coef_)+intercept_

0.1706631179387189