In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day29-sklearn-pipelines/train.csv")

In [3]:
df.sample(5)

PassengerId  Survived  Pclass  \
426          427         1       2   
150          151         0       2   
184          185         1       3   
66            67         1       2   
645          646         1       1   

                                            Name     Sex   Age  SibSp  Parch  \
426  Clarke, Mrs. Charles V (Ada Maria Winfield)  female  28.0      1      0   
150                   Bateman, Rev. Robert James    male  51.0      0      0   
184          Kink-Heilmann, Miss. Luise Gretchen  female   4.0      0      2   
66                  Nye, Mrs. (Elizabeth Ramell)  female  29.0      0      0   
645                    Harper, Mr. Henry Sleeper    male  48.0      1      0   

          Ticket     Fare Cabin Embarked  
426         2003  26.0000   NaN        S  
150  S.O.P. 1166  12.5250   NaN        S  
184       315153  22.0250   NaN        S  
66    C.A. 29395  10.5000   F33        S  
645     PC 17572  76.7292   D33        C

In [4]:
df.drop(["PassengerId","Name","Cabin","Ticket"],inplace=True,axis=1)

In [5]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [6]:
x=df.drop("Survived",axis=1)

In [7]:
y=df["Survived"]

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=43)

In [27]:
x_test

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
770       3    male  24.0      0      0   9.5000        S
853       1  female  16.0      0      1  39.4000        S
144       2    male  18.0      0      0  11.5000        S
141       3  female  22.0      0      0   7.7500        S
261       3    male   3.0      4      2  31.3875        S
..      ...     ...   ...    ...    ...      ...      ...
71        3  female  16.0      5      2  46.9000        S
423       3  female  28.0      1      1  14.4000        S
342       2    male  28.0      0      0  13.0000        S
825       3    male   NaN      0      0   6.9500        Q
293       3  female  24.0      0      0   8.8500        S

[179 rows x 7 columns]

In [9]:
si_age=SimpleImputer()
si_embarked=SimpleImputer(strategy="most_frequent")

In [10]:
x_train_age=si_age.fit_transform(x_train[["Age"]])
x_train_embarked=si_embarked.fit_transform(x_train[["Embarked"]])
x_test_age=si_age.transform(x_test[["Age"]])
x_test_embarked=si_embarked.transform(x_test[["Embarked"]])

In [11]:
x_train_age

array([[30.16725217],
       [32.        ],
       [36.        ],
       [36.        ],
       [30.16725217],
       [26.        ],
       [30.16725217],
       [17.        ],
       [24.        ],
       [30.        ],
       [ 3.        ],
       [44.        ],
       [18.        ],
       [35.        ],
       [39.        ],
       [45.        ],
       [14.        ],
       [30.5       ],
       [38.        ],
       [27.        ],
       [38.        ],
       [30.16725217],
       [30.16725217],
       [30.16725217],
       [30.16725217],
       [29.        ],
       [18.        ],
       [23.        ],
       [30.16725217],
       [36.        ],
       [30.16725217],
       [24.        ],
       [27.        ],
       [30.16725217],
       [24.        ],
       [22.        ],
       [ 2.        ],
       [30.16725217],
       [29.        ],
       [14.        ],
       [24.        ],
       [39.        ],
       [58.        ],
       [30.16725217],
       [30.16725217],
       [16

In [12]:
ohe_sex=OneHotEncoder(sparse=False,handle_unknown="ignore")
ohe_embarked=OneHotEncoder(sparse=False,handle_unknown="ignore")

x_train_sex=ohe_sex.fit_transform(x_train[["Sex"]])
x_train_embarked=ohe_embarked.fit_transform(x_train_embarked)

x_test_sex=ohe_sex.fit_transform(x_test[["Sex"]])
x_test_embarked=ohe_embarked.fit_transform(x_test_embarked)

In [13]:
x_train_sex

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [14]:
x_train_rem=x_train.drop(columns=["Sex","Age","Embarked"])
x_test_rem=x_test.drop(columns=["Sex","Age","Embarked"])

In [15]:
x_train_transform=np.concatenate((x_train_rem,x_train_sex,x_train_embarked,x_train_age),axis=1)
x_test_transform=np.concatenate((x_test_rem,x_test_sex,x_test_embarked,x_test_age),axis=1)

In [16]:
x_train_transform.shape

(712, 10)

In [17]:
x_test_transform.shape

(179, 10)

In [18]:
clf=DecisionTreeClassifier()
clf.fit(x_train_transform,y_train)

DecisionTreeClassifier()

array([[ 3.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 24.        ],
       [ 1.        ,  0.        ,  1.        , ...,  0.        ,
         1.        , 16.        ],
       [ 2.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 18.        ],
       ...,
       [ 2.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 28.        ],
       [ 3.        ,  0.        ,  0.        , ...,  1.        ,
         0.        , 30.16725217],
       [ 3.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 24.        ]])

In [19]:
y_prd=clf.predict(x_test_transform)

In [20]:
y_prd

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_prd)

0.7821229050279329

In [22]:
import pickle

In [23]:
# with open("model_ohe_sex.pkl","wb") as file:
#     pickle.dump(ohe_sex,file)
# with open("model/ohe_embarked.pkl","wb") as file:
#     pickle.dump(ohe_embarked,file)
# with open("model/clf.pkl","wb") as file:
#     pickle.dump(clf,file)

In [24]:
pickle.dump(ohe_sex,open("model_ohe_sex.pkl","wb"))
pickle.dump(ohe_embarked,open("model_ohe_embarked.pkl","wb"))
pickle.dump(clf,open("model_clf.pkl","wb"))

In [26]:
x=pickle.load(open("model_clf.pkl","rb"))

In [30]:
x

DecisionTreeClassifier()

In [29]:
x.predict(x_test_transform)

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0], dtype=int64)