In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

C:\Users\Abdur rahim nishad\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Abdur rahim nishad\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\Abdur rahim nishad\anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
df=pd.read_csv("https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day29-sklearn-pipelines/train.csv")

In [3]:
df.sample(5)

PassengerId  Survived  Pclass                                       Name  \
262          263         0       1                          Taussig, Mr. Emil   
347          348         1       3  Davison, Mrs. Thomas Henry (Mary E Finck)   
229          230         0       3                    Lefebre, Miss. Mathilde   
448          449         1       3             Baclini, Miss. Marie Catherine   
818          819         0       3           Holm, Mr. John Fredrik Alexander   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
262    male  52.0      1      1  110413  79.6500   E67        S  
347  female   NaN      1      0  386525  16.1000   NaN        S  
229  female   NaN      3      1    4133  25.4667   NaN        S  
448  female   5.0      2      1    2666  19.2583   NaN        C  
818    male  43.0      0      0  C 7075   6.4500   NaN        S

In [4]:
df.drop(["PassengerId","Name","Cabin","Ticket"],inplace=True,axis=1)

In [5]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [6]:
x=df.drop("Survived",axis=1)

In [7]:
y=df["Survived"]

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=43)

In [9]:
x_test

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
770       3    male  24.0      0      0   9.5000        S
853       1  female  16.0      0      1  39.4000        S
144       2    male  18.0      0      0  11.5000        S
141       3  female  22.0      0      0   7.7500        S
261       3    male   3.0      4      2  31.3875        S
..      ...     ...   ...    ...    ...      ...      ...
71        3  female  16.0      5      2  46.9000        S
423       3  female  28.0      1      1  14.4000        S
342       2    male  28.0      0      0  13.0000        S
825       3    male   NaN      0      0   6.9500        Q
293       3  female  24.0      0      0   8.8500        S

[179 rows x 7 columns]

In [10]:
si_age=SimpleImputer()
si_embarked=SimpleImputer(strategy="most_frequent")

In [11]:
x_train_age=si_age.fit_transform(x_train[["Age"]])
x_train_embarked=si_embarked.fit_transform(x_train[["Embarked"]])
x_test_age=si_age.transform(x_test[["Age"]])
x_test_embarked=si_embarked.transform(x_test[["Embarked"]])

In [12]:
x_train_age

array([[30.16725217],
       [32.        ],
       [36.        ],
       [36.        ],
       [30.16725217],
       [26.        ],
       [30.16725217],
       [17.        ],
       [24.        ],
       [30.        ],
       [ 3.        ],
       [44.        ],
       [18.        ],
       [35.        ],
       [39.        ],
       [45.        ],
       [14.        ],
       [30.5       ],
       [38.        ],
       [27.        ],
       [38.        ],
       [30.16725217],
       [30.16725217],
       [30.16725217],
       [30.16725217],
       [29.        ],
       [18.        ],
       [23.        ],
       [30.16725217],
       [36.        ],
       [30.16725217],
       [24.        ],
       [27.        ],
       [30.16725217],
       [24.        ],
       [22.        ],
       [ 2.        ],
       [30.16725217],
       [29.        ],
       [14.        ],
       [24.        ],
       [39.        ],
       [58.        ],
       [30.16725217],
       [30.16725217],
       [16

In [13]:
ohe_sex=OneHotEncoder(sparse=False,handle_unknown="ignore")
ohe_embarked=OneHotEncoder(sparse=False,handle_unknown="ignore")

x_train_sex=ohe_sex.fit_transform(x_train[["Sex"]])
x_train_embarked=ohe_embarked.fit_transform(x_train_embarked)

x_test_sex=ohe_sex.fit_transform(x_test[["Sex"]])
x_test_embarked=ohe_embarked.fit_transform(x_test_embarked)

C:\Users\Abdur rahim nishad\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\Abdur rahim nishad\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\Abdur rahim nishad\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\Abdur rahim nishad\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse

In [14]:
x_train_sex

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [15]:
x_train_rem=x_train.drop(columns=["Sex","Age","Embarked"])
x_test_rem=x_test.drop(columns=["Sex","Age","Embarked"])

In [16]:
x_train_transform=np.concatenate((x_train_rem,x_train_sex,x_train_embarked,x_train_age),axis=1)
x_test_transform=np.concatenate((x_test_rem,x_test_sex,x_test_embarked,x_test_age),axis=1)

In [17]:
x_train_transform.shape

(712, 10)

In [18]:
x_test_transform.shape

(179, 10)

In [29]:
x_test_transform

array([[ 3.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 24.        ],
       [ 1.        ,  0.        ,  1.        , ...,  0.        ,
         1.        , 16.        ],
       [ 2.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 18.        ],
       ...,
       [ 2.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 28.        ],
       [ 3.        ,  0.        ,  0.        , ...,  1.        ,
         0.        , 30.16725217],
       [ 3.        ,  0.        ,  0.        , ...,  0.        ,
         1.        , 24.        ]])

In [30]:
pd.DataFrame(x_test_transform)

0    1    2        3    4    5    6    7    8          9
0    3.0  0.0  0.0   9.5000  0.0  1.0  0.0  0.0  1.0  24.000000
1    1.0  0.0  1.0  39.4000  1.0  0.0  0.0  0.0  1.0  16.000000
2    2.0  0.0  0.0  11.5000  0.0  1.0  0.0  0.0  1.0  18.000000
3    3.0  0.0  0.0   7.7500  1.0  0.0  0.0  0.0  1.0  22.000000
4    3.0  4.0  2.0  31.3875  0.0  1.0  0.0  0.0  1.0   3.000000
..   ...  ...  ...      ...  ...  ...  ...  ...  ...        ...
174  3.0  5.0  2.0  46.9000  1.0  0.0  0.0  0.0  1.0  16.000000
175  3.0  1.0  1.0  14.4000  1.0  0.0  0.0  0.0  1.0  28.000000
176  2.0  0.0  0.0  13.0000  0.0  1.0  0.0  0.0  1.0  28.000000
177  3.0  0.0  0.0   6.9500  0.0  1.0  0.0  1.0  0.0  30.167252
178  3.0  0.0  0.0   8.8500  1.0  0.0  0.0  0.0  1.0  24.000000

[179 rows x 10 columns]

In [32]:
y_test

770    0
853    1
144    0
141    1
261    1
      ..
71     0
423    0
342    0
825    0
293    0
Name: Survived, Length: 179, dtype: int64

In [19]:
clf=DecisionTreeClassifier()
clf.fit(x_train_transform,y_train)

DecisionTreeClassifier()

In [20]:
y_prd=clf.predict(x_test_transform)

In [21]:
y_prd

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [22]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_prd)

0.776536312849162

In [23]:
import pickle

In [24]:
# with open("model_ohe_sex.pkl","wb") as file:
#     pickle.dump(ohe_sex,file)
# with open("model/ohe_embarked.pkl","wb") as file:
#     pickle.dump(ohe_embarked,file)
# with open("model/clf.pkl","wb") as file:
#     pickle.dump(clf,file)

In [25]:
pickle.dump(ohe_sex,open("model_ohe_sex.pkl","wb"))
pickle.dump(ohe_embarked,open("model_ohe_embarked.pkl","wb"))
pickle.dump(clf,open("model_clf.pkl","wb"))

In [26]:
x=pickle.load(open("model_clf.pkl","rb"))

In [27]:
x

DecisionTreeClassifier()

In [28]:
x.predict(x_test_transform)

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0], dtype=int64)

In [31]:
x.predict([[3,0,0,9.5,0,1,0,0,1,24]])

array([0], dtype=int64)